### ISSUE TITLE
Command for running a temporary container

### ISSUE THREAD

**Issue by riscie** [eldada/kubernetes-scripts#1]
Hi there

Fine list of scripts, thank you for these.

I would have one addition. The use of the generator flag throws a warning because it has been deprecated.
`kubectl run --generator=run-pod/v1 my-ubuntu --rm -i -t --image ubuntu -- bash`

I think we should use the command like this now:
`kubectl run my-ubuntu --rm -i -t --image ubuntu -- bash`

Not sure if it helps, just an input ;)

kindly, riscie

**Comment by eldada** [comment]
Thx @riscie !
I tried but get the same warning 
```
~ kubectl run my-ubuntu --rm -i -t --image ubuntu -- bash

kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
root@my-ubuntu-654fdbf6ff-hxxfm:/# 
```

I actually found that using `--restart=Never` also solves this.
```
~ kubectl run my-ubuntu --rm --restart=Never -i -t --image ubuntu -- bash

If you don't see a command prompt, try pressing enter.
root@my-ubuntu:/#
```

I will update my examples.
