### ISSUE TITLE
[feature requests] pod logs, copy pod files

### ISSUE THREAD

**Issue by LeiYangGH** [eldada/kubernetes-scripts#14]
hi thanks for these useful scripts.
in my daily work, i most often 

- logs pod xxx
- cp podname:somepath/ somelocalfolder

could you also add such scripts?
some configurations of which name pattern pods need logs, and internal directory to copy is prefered.

thanks!

**Comment by eldada** [comment]
Can you explain more?
For getting pod logs, you just use 
```
kubectel logs <pod>
```

For copying out of a pod
```
kubectl cp <pod>:<pod-path-to-file> <local-path-to-file>
```

So what kind of added functionality on top of this are you looking for?

**Comment by LeiYangGH** [comment]
i think this could be useful: 
multiple replicas(pods) of same deployment, log each and redirect to file with pod name in file name.
similiarly, pods internal files copied to parent folder with pod name as part.
if we can specify the deployment name then script iterate each running pod then it is will save a lot of time.

**Comment by eldada** [comment]
Are you familiar with [stern](https://github.com/stern/stern)?
This is a very powerful tool for getting logs. Also for multiple replicas...

**Comment by LeiYangGH** [comment]
thanks, i tried [kubetail](https://github.com/johanhaleby/kubetail) before asking this question.
after testing, i think stern satisfies most of my needs, and maybe need myself do some customization.
